"use client";
import { useRouter } from "next/navigation";
import { useState } from "react";
type Theatre = { id: number; title: string };
function MediaForm({ kind, theatres, refresh }: { kind: "reel" | "story"; theatres: Theatre[]; refresh: () => void }) {
  const [url, setUrl] = useState(""); const [message, setMessage] = useState(""); const [uploading, setUploading] = useState(false);
  async function upload(event: React.ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; setUploading(true); setMessage("Uploading…"); const data = new FormData(); data.append("file", file); data.append("folder", "reels"); const response = await fetch("/api/upload", { method: "POST", body: data }); const result = await response.json().catch(() => null); setUploading(false); if (!response.ok) setMessage(result?.error || "Upload failed."); else { setUrl(result.url); setMessage("Video uploaded."); } }
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setMessage("Publishing…"); const response = await fetch("/api/admin/media", { method: "POST", body: new FormData(event.currentTarget) }); setMessage(response.ok ? "Published." : (await response.json().catch(() => null))?.error || "Unable to publish."); if (response.ok) { event.currentTarget.reset(); setUrl(""); refresh(); } }
  return <form className="admin-media-form" onSubmit={submit}><input type="hidden" name="kind" value={kind} /><div className="admin-media-form-title"><span className={`media-type-pill ${kind}`}>{kind.toUpperCase()}</span><h3>{kind === "reel" ? "Add Theatre Reel" : "Add TheatreHub Story"}</h3><p>{kind === "reel" ? "Share a stage video by URL or upload a file." : "Post a photo and caption for the story row."}</p></div><label>Theatre<select name="theatreId" required defaultValue=""><option value="" disabled>Select theatre</option>{theatres.map((theatre) => <option key={theatre.id} value={theatre.id}>{theatre.title}</option>)}</select></label><label>Title<input name="title" required placeholder={kind === "reel" ? "Opening night" : "Behind the scenes"} /></label><label>{kind === "reel" ? "Video URL" : "Image URL"}<input name="url" type="url" required value={url} onChange={(event) => setUrl(event.target.value)} placeholder="https://…" /></label>{kind === "reel" && <label className="media-upload-label">Or upload video<input type="file" accept="video/mp4,video/webm,video/quicktime" onChange={upload} disabled={uploading} /><small>{uploading ? "Uploading…" : "MP4, WebM or MOV up to 100MB"}</small></label>}{kind === "story" && <label>Caption (optional)<textarea name="caption" placeholder="Add a short caption" /></label>}<button className="admin-media-submit" disabled={!theatres.length || uploading}>Publish {kind} <span>→</span></button><span role="status">{message}</span></form>;
}
export function AdminMediaManager({ theatres }: { theatres: Theatre[] }) { const router = useRouter(); return <div className="admin-media-manager"><div className="admin-media-form-grid"><MediaForm kind="reel" theatres={theatres} refresh={() => router.refresh()} /><MediaForm kind="story" theatres={theatres} refresh={() => router.refresh()} /></div></div>; }
